use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use crate::cli::RunOptions;
use crate::model::{EffectiveSettings, SourcedValue, WriteMode};

pub type AppResult<T> = Result<T, Box<dyn std::error::Error>>;

#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct DefaultsFile {
    pub entries: BTreeMap<String, Vec<String>>,
}

impl DefaultsFile {
    pub fn load(path: &Path) -> AppResult<Self> {
        if !path.exists() {
            return Ok(Self::default());
        }

        let mut entries = BTreeMap::new();
        let content = fs::read_to_string(path)?;
        for raw_line in content.lines() {
            let line = raw_line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            let Some((key, value)) = line.split_once('=') else {
                continue;
            };

            entries
                .entry(key.trim().to_string())
                .or_insert_with(Vec::new)
                .push(value.trim().to_string());
        }

        Ok(Self { entries })
    }

    pub fn save(&self, path: &Path) -> AppResult<()> {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }

        let mut content = String::new();
        content.push_str("# Generated by Valkyrie.\n");
        content.push_str("# Prefer `valkyrie defaults set ...` over hand-editing this file.\n");

        for (key, values) in &self.entries {
            for value in values {
                content.push_str(key);
                content.push('=');
                content.push_str(value);
                content.push('\n');
            }
        }

        fs::write(path, content)?;
        Ok(())
    }

    pub fn set(&mut self, key: &str, value: String) {
        if is_multi_value_key(key) {
            self.entries
                .entry(key.to_string())
                .or_insert_with(Vec::new)
                .push(value);
        } else {
            self.entries.insert(key.to_string(), vec![value]);
        }
    }

    pub fn unset(&mut self, key: &str) {
        self.entries.remove(key);
    }

    pub fn get(&self, key: &str) -> Option<&Vec<String>> {
        self.entries.get(key)
    }

    pub fn render_human(&self) -> String {
        if self.entries.is_empty() {
            return "No defaults saved.".to_string();
        }

        let mut output = String::new();
        for (key, values) in &self.entries {
            for value in values {
                output.push_str(key);
                output.push_str(" = ");
                output.push_str(value);
                output.push('\n');
            }
        }
        output.trim_end().to_string()
    }

    pub fn export_yaml(&self) -> String {
        let mut lines = vec![
            "# .valkyrie/defaults.yaml".to_string(),
            "# Generated by `valkyrie defaults export`.".to_string(),
            "# Prefer `valkyrie defaults set ...` over hand-editing this file.".to_string(),
        ];

        let mut grouped: BTreeMap<String, BTreeMap<String, Vec<String>>> = BTreeMap::new();
        for (key, values) in &self.entries {
            let mut parts = key.splitn(2, '.');
            let top = parts.next().unwrap_or("misc").to_string();
            let leaf = parts.next().unwrap_or("value").to_string();
            grouped
                .entry(top)
                .or_default()
                .entry(leaf)
                .or_default()
                .extend(values.clone());
        }

        for (section, values) in grouped {
            lines.push(format!("{section}:"));
            for (leaf, entries) in values {
                if entries.len() == 1 {
                    lines.push(format!("  {leaf}: {}", yaml_scalar(&entries[0])));
                } else {
                    lines.push(format!("  {leaf}:"));
                    for entry in entries {
                        lines.push(format!("    - {}", yaml_scalar(&entry)));
                    }
                }
            }
        }

        lines.join("\n")
    }
}

pub fn repo_defaults_path(repo_path: &Path) -> PathBuf {
    repo_path.join(".valkyrie").join("defaults.conf")
}

pub fn user_defaults_path() -> PathBuf {
    let base = env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| env::var_os("HOME").map(|home| PathBuf::from(home).join(".config")))
        .unwrap_or_else(|| PathBuf::from("."));
    base.join("valkyrie").join("defaults.conf")
}

pub fn resolve_settings(repo_path: PathBuf, options: &RunOptions) -> AppResult<EffectiveSettings> {
    let repo_defaults = DefaultsFile::load(&repo_defaults_path(&repo_path))?;
    let user_defaults = DefaultsFile::load(&user_defaults_path())?;

    let repo_path_value = SourcedValue {
        value: repo_path.clone(),
        source: if options.repo.is_some() {
            "cli".to_string()
        } else {
            "cwd".to_string()
        },
    };

    let base_branch = resolve_string(
        "repo.base",
        options.base.clone(),
        &repo_defaults,
        &user_defaults,
        env::var("VALKYRIE_BASE").ok(),
        "main".to_string(),
    );

    let validation_commands =
        resolve_validation_commands(&repo_path, options, &repo_defaults, &user_defaults);

    let write_commit = resolve_bool(
        "write.commit",
        options.commit,
        &repo_defaults,
        &user_defaults,
        env::var("VALKYRIE_COMMIT").ok(),
        false,
    );
    let write_push = resolve_bool(
        "write.push",
        options.push,
        &repo_defaults,
        &user_defaults,
        env::var("VALKYRIE_PUSH").ok(),
        false,
    );
    let write_open_pr = resolve_bool(
        "write.open_pr",
        options.open_pr,
        &repo_defaults,
        &user_defaults,
        env::var("VALKYRIE_OPEN_PR").ok(),
        false,
    );
    let write_post_comment = resolve_bool(
        "write.post_comment",
        options.post_comment,
        &repo_defaults,
        &user_defaults,
        env::var("VALKYRIE_POST_COMMENT").ok(),
        false,
    );

    let max_iterations = resolve_u32(
        "limits.max_iterations",
        options.max_iterations,
        &repo_defaults,
        &user_defaults,
        env::var("VALKYRIE_MAX_ITERATIONS").ok(),
        8,
    );

    let max_files_changed = resolve_u32(
        "limits.max_files_changed",
        options.max_files,
        &repo_defaults,
        &user_defaults,
        env::var("VALKYRIE_MAX_FILES_CHANGED").ok(),
        25,
    );

    let timeout_minutes = resolve_u64(
        "limits.timeout_minutes",
        options.timeout_minutes,
        &repo_defaults,
        &user_defaults,
        env::var("VALKYRIE_TIMEOUT_MINUTES").ok(),
        60,
    );

    let write_mode = determine_write_mode(options, &write_commit, &write_push, &write_open_pr);

    Ok(EffectiveSettings {
        repo_path: repo_path_value,
        base_branch,
        validation_commands,
        write_commit,
        write_push,
        write_open_pr,
        write_post_comment,
        max_iterations,
        max_files_changed,
        timeout_minutes,
        dry_run: options.dry_run,
        skip_validation: options.skip_validation,
        verbose: options.verbose,
        json: options.json,
        tui: options.tui,
        write_mode,
    })
}

fn determine_write_mode(
    options: &RunOptions,
    commit: &SourcedValue<bool>,
    push: &SourcedValue<bool>,
    open_pr: &SourcedValue<bool>,
) -> WriteMode {
    if options.no_write {
        WriteMode::NoWrite
    } else if open_pr.value {
        WriteMode::PullRequest
    } else if push.value {
        WriteMode::Push
    } else if commit.value {
        WriteMode::Commit
    } else {
        WriteMode::LocalPatch
    }
}

fn resolve_validation_commands(
    repo_path: &Path,
    options: &RunOptions,
    repo_defaults: &DefaultsFile,
    user_defaults: &DefaultsFile,
) -> Vec<SourcedValue<String>> {
    if !options.validation_commands.is_empty() {
        return options
            .validation_commands
            .iter()
            .cloned()
            .map(|value| SourcedValue {
                value,
                source: "cli".to_string(),
            })
            .collect();
    }

    if let Ok(env_value) = env::var("VALKYRIE_VALIDATE") {
        let values = env_value
            .split(';')
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .map(|value| SourcedValue {
                value: value.to_string(),
                source: "env".to_string(),
            })
            .collect::<Vec<_>>();
        if !values.is_empty() {
            return values;
        }
    }

    if let Some(values) = repo_defaults.get("validation.command") {
        return values
            .iter()
            .cloned()
            .map(|value| SourcedValue {
                value,
                source: "repo default".to_string(),
            })
            .collect();
    }

    if let Some(values) = user_defaults.get("validation.command") {
        return values
            .iter()
            .cloned()
            .map(|value| SourcedValue {
                value,
                source: "user default".to_string(),
            })
            .collect();
    }

    infer_validation_commands(repo_path)
}

fn infer_validation_commands(repo_path: &Path) -> Vec<SourcedValue<String>> {
    let mut inferred = Vec::new();

    if repo_path.join("Cargo.toml").exists() {
        inferred.push(SourcedValue {
            value: "cargo test".to_string(),
            source: "inferred from Cargo.toml".to_string(),
        });
        inferred.push(SourcedValue {
            value: "cargo fmt --check".to_string(),
            source: "inferred from Cargo.toml".to_string(),
        });
    }

    if repo_path.join("package.json").exists() {
        inferred.push(SourcedValue {
            value: "npm test".to_string(),
            source: "inferred from package.json".to_string(),
        });
    }

    if repo_path.join("pyproject.toml").exists() {
        inferred.push(SourcedValue {
            value: "pytest".to_string(),
            source: "inferred from pyproject.toml".to_string(),
        });
    }

    inferred
}

fn resolve_string(
    key: &str,
    cli_value: Option<String>,
    repo_defaults: &DefaultsFile,
    user_defaults: &DefaultsFile,
    env_value: Option<String>,
    builtin: String,
) -> SourcedValue<String> {
    if let Some(value) = cli_value {
        return SourcedValue {
            value,
            source: "cli".to_string(),
        };
    }

    if let Some(value) = env_value {
        return SourcedValue {
            value,
            source: "env".to_string(),
        };
    }

    if let Some(value) = repo_defaults.get(key).and_then(|values| values.first()) {
        return SourcedValue {
            value: value.clone(),
            source: "repo default".to_string(),
        };
    }

    if let Some(value) = user_defaults.get(key).and_then(|values| values.first()) {
        return SourcedValue {
            value: value.clone(),
            source: "user default".to_string(),
        };
    }

    SourcedValue {
        value: builtin,
        source: "builtin".to_string(),
    }
}

fn resolve_bool(
    key: &str,
    cli_flag: bool,
    repo_defaults: &DefaultsFile,
    user_defaults: &DefaultsFile,
    env_value: Option<String>,
    builtin: bool,
) -> SourcedValue<bool> {
    if cli_flag {
        return SourcedValue {
            value: true,
            source: "cli".to_string(),
        };
    }

    if let Some(value) = env_value.and_then(|item| parse_bool(&item)) {
        return SourcedValue {
            value,
            source: "env".to_string(),
        };
    }

    if let Some(value) = repo_defaults
        .get(key)
        .and_then(|values| values.first())
        .and_then(|value| parse_bool(value))
    {
        return SourcedValue {
            value,
            source: "repo default".to_string(),
        };
    }

    if let Some(value) = user_defaults
        .get(key)
        .and_then(|values| values.first())
        .and_then(|value| parse_bool(value))
    {
        return SourcedValue {
            value,
            source: "user default".to_string(),
        };
    }

    SourcedValue {
        value: builtin,
        source: "builtin".to_string(),
    }
}

fn resolve_u32(
    key: &str,
    cli_value: Option<u32>,
    repo_defaults: &DefaultsFile,
    user_defaults: &DefaultsFile,
    env_value: Option<String>,
    builtin: u32,
) -> SourcedValue<u32> {
    if let Some(value) = cli_value {
        return SourcedValue {
            value,
            source: "cli".to_string(),
        };
    }

    if let Some(value) = env_value.and_then(|item| item.parse::<u32>().ok()) {
        return SourcedValue {
            value,
            source: "env".to_string(),
        };
    }

    if let Some(value) = repo_defaults
        .get(key)
        .and_then(|values| values.first())
        .and_then(|value| value.parse::<u32>().ok())
    {
        return SourcedValue {
            value,
            source: "repo default".to_string(),
        };
    }

    if let Some(value) = user_defaults
        .get(key)
        .and_then(|values| values.first())
        .and_then(|value| value.parse::<u32>().ok())
    {
        return SourcedValue {
            value,
            source: "user default".to_string(),
        };
    }

    SourcedValue {
        value: builtin,
        source: "builtin".to_string(),
    }
}

fn resolve_u64(
    key: &str,
    cli_value: Option<u64>,
    repo_defaults: &DefaultsFile,
    user_defaults: &DefaultsFile,
    env_value: Option<String>,
    builtin: u64,
) -> SourcedValue<u64> {
    if let Some(value) = cli_value {
        return SourcedValue {
            value,
            source: "cli".to_string(),
        };
    }

    if let Some(value) = env_value.and_then(|item| item.parse::<u64>().ok()) {
        return SourcedValue {
            value,
            source: "env".to_string(),
        };
    }

    if let Some(value) = repo_defaults
        .get(key)
        .and_then(|values| values.first())
        .and_then(|value| value.parse::<u64>().ok())
    {
        return SourcedValue {
            value,
            source: "repo default".to_string(),
        };
    }

    if let Some(value) = user_defaults
        .get(key)
        .and_then(|values| values.first())
        .and_then(|value| value.parse::<u64>().ok())
    {
        return SourcedValue {
            value,
            source: "user default".to_string(),
        };
    }

    SourcedValue {
        value: builtin,
        source: "builtin".to_string(),
    }
}

fn parse_bool(value: &str) -> Option<bool> {
    match value.trim().to_ascii_lowercase().as_str() {
        "1" | "true" | "yes" | "on" => Some(true),
        "0" | "false" | "no" | "off" => Some(false),
        _ => None,
    }
}

fn is_multi_value_key(key: &str) -> bool {
    matches!(key, "validation.command")
}

fn yaml_scalar(value: &str) -> String {
    if value
        .chars()
        .all(|item| item.is_ascii_alphanumeric() || matches!(item, '-' | '_' | '.'))
    {
        value.to_string()
    } else {
        format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
    }
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::time::{SystemTime, UNIX_EPOCH};

    use super::{DefaultsFile, repo_defaults_path};

    #[test]
    fn defaults_roundtrip() {
        let temp = unique_temp_dir("defaults");
        fs::create_dir_all(temp.join(".valkyrie")).expect("create");
        let path = repo_defaults_path(&temp);

        let mut defaults = DefaultsFile::default();
        defaults.set("repo.base", "main".into());
        defaults.set("validation.command", "cargo test".into());
        defaults.set("validation.command", "cargo fmt --check".into());
        defaults.save(&path).expect("save");

        let loaded = DefaultsFile::load(&path).expect("load");
        assert_eq!(
            loaded.get("repo.base").expect("repo base"),
            &vec!["main".to_string()]
        );
        assert_eq!(
            loaded.get("validation.command").expect("validation").len(),
            2
        );
    }

    fn unique_temp_dir(name: &str) -> std::path::PathBuf {
        let suffix = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time")
            .as_nanos();
        std::env::temp_dir().join(format!("valkyrie-{name}-{suffix}"))
    }
}
